name: RDP-Ubuntu

on:
  workflow_dispatch:

jobs:
  secure-rdp-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Update system
        run: |
          sudo apt-get update -y

      - name: Install desktop and RDP server
        run: |
          sudo apt-get install -y xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils
          sudo apt-get install -y xrdp
          echo xfce4-session > ~/.xsession
          sudo systemctl enable xrdp
          sudo systemctl restart xrdp

      - name: Create RDP user
        run: |
          PASS=$(openssl rand -base64 12)
          sudo useradd -m -s /bin/bash rdpuser
          echo "rdpuser:$PASS" | sudo chpasswd
          echo "RDP_USER=rdpuser" >> $GITHUB_ENV
          echo "RDP_PASS=$PASS" >> $GITHUB_ENV
          echo "✅ Created user 'rdpuser' with password: $PASS"

      - name: Install and start Tailscale
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          curl -fsSL https://tailscale.com/install.sh | sudo sh
          sudo tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
          sleep 3
          sudo tailscale up --authkey=${TAILSCALE_AUTH_KEY} --hostname="gh-rdp-${GITHUB_RUN_ID}"
          echo "TAILSCALE_IP=$(sudo tailscale ip -4)" >> $GITHUB_ENV

      - name: Show connection info
        run: |
          echo ""
          echo "=========================="
          echo "✅ RDP Access Information"
          echo "IP Address : $TAILSCALE_IP"
          echo "Username   : $RDP_USER"
          echo "Password   : $RDP_PASS"
          echo "=========================="
          echo ""
          echo "Leave this workflow running to keep the RDP session alive."

      - name: Keep alive
        run: |
          while true; do
            echo "[ $(date) ] RDP session active..."
            sleep 300
          done
