name: Ubuntu RDP

on:
  workflow_dispatch:

jobs:
  ubuntu-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Install XRDP and Desktop Environment
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xrdp xfce4 xfce4-goodies dbus-x11
          
          # Allow RDP through firewall
          sudo ufw allow 3389/tcp
          sudo ufw --force enable

      - name: Create RDP User with Fixed Password
        run: |
          # Create user with fixed password
          sudo useradd -m -s /bin/bash rdpuser
          echo "rdpuser:*m96319631Z-" | sudo chpasswd
          
          # Add user to sudo group for admin access
          sudo usermod -aG sudo rdpuser
          
          # Configure Xfce for XRDP - use startxfce4 instead of xfce4-session
          echo "startxfce4" | sudo tee /home/rdpuser/.xsession
          sudo chmod +x /home/rdpuser/.xsession
          sudo chown rdpuser:rdpuser /home/rdpuser/.xsession
          
          # Also create .xinitrc for backup
          echo "#!/bin/sh" | sudo tee /home/rdpuser/.xinitrc
          echo "exec startxfce4" | sudo tee -a /home/rdpuser/.xinitrc
          sudo chmod +x /home/rdpuser/.xinitrc
          sudo chown rdpuser:rdpuser /home/rdpuser/.xinitrc
          
          # Configure XRDP to use the startwm script properly
          sudo sed -i 's|^test -x /etc/X11/Xsession && exec /etc/X11/Xsession|startxfce4|g' /etc/xrdp/startwm.sh
          sudo sed -i 's|^exec /bin/sh /etc/X11/Xsession|startxfce4|g' /etc/xrdp/startwm.sh
          
          # Verify user creation
          if ! id rdpuser &>/dev/null; then
              echo "User creation failed"
              exit 1
          fi
          
          echo "RDP_CREDS=User: rdpuser | Password: *m96319631Z-" >> $GITHUB_ENV
          
          # Restart XRDP service after configuration
          sudo systemctl enable xrdp
          sudo systemctl restart xrdp

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Establish Tailscale Connection
        run: |
          # Start Tailscale with auth key
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-ubuntu-${{ github.run_id }}
          
          # Wait for IP assignment
          retries=0
          while [ -z "$TSIP" ] && [ $retries -lt 10 ]; do
              TSIP=$(tailscale ip -4)
              sleep 5
              retries=$((retries + 1))
          done
          
          if [ -z "$TSIP" ]; then
              echo "Tailscale IP not assigned. Exiting."
              exit 1
          fi
          
          echo "TAILSCALE_IP=$TSIP" >> $GITHUB_ENV
          echo "Tailscale IP: $TSIP"

      - name: Verify RDP Accessibility
        run: |
          echo "Tailscale IP: $TAILSCALE_IP"
          
          # Check if XRDP is listening on port 3389
          if ! sudo netstat -tuln | grep :3389; then
              echo "XRDP is not listening on port 3389"
              exit 1
          fi
          
          echo "XRDP service is running and listening on port 3389"

      - name: Maintain Connection
        run: |
          echo ""
          echo "=== RDP ACCESS ==="
          echo "Address: $TAILSCALE_IP"
          echo "Username: rdpuser"
          echo "Password: *m96319631Z-"
          echo "=================="
          echo ""
          
          # Keep runner active
          while true; do
              echo "[$(date)] RDP Active - Use workflow cancel button to terminate"
              sleep 300
          done
