name: Ubuntu RDP

on:
  workflow_dispatch:

jobs:
  ubuntu-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: نصب XRDP و محیط دسکتاپ
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            xrdp \
            lxde-core \
            lxde \
            dbus-x11 \
            x11-xserver-utils \
            lightdm
          
          sudo ufw allow 3389/tcp
          sudo ufw --force enable

      - name: ایجاد کاربر RDP و پیکربندی LXDE
        run: |
          sudo useradd -m -s /bin/bash rdpuser
          echo "rdpuser:*m96319631Z-" | sudo chpasswd
          sudo usermod -aG sudo rdpuser

          echo "startlxde" | sudo tee /home/rdpuser/.xsession
          sudo chmod +x /home/rdpuser/.xsession
          sudo chown rdpuser:rdpuser /home/rdpuser/.xsession

          # ایجاد فایل startwm.sh بدون heredoc
          sudo bash -c 'printf "%s\n" "#!/bin/sh" \
          "if [ -r /etc/default/locale ]; then" \
          "  . /etc/default/locale" \
          "  export LANG LANGUAGE" \
          "fi" \
          "" \
          "if [ -r /etc/profile ]; then . /etc/profile; fi" \
          "" \
          "if [ -r \"$HOME/.xsession\" ]; then" \
          "  . \"$HOME/.xsession\"" \
          "elif [ -r /etc/X11/Xsession ]; then" \
          "  . /etc/X11/Xsession" \
          "fi" > /etc/xrdp/startwm.sh'

          sudo chmod +x /etc/xrdp/startwm.sh
          sudo sed -i 's/^allowed_users=console/allowed_users=any/' /etc/X11/Xwrapper.config

          if ! id rdpuser &>/dev/null; then
            echo "ایجاد کاربر ناموفق بود"
            exit 1
          fi

          echo "RDP_CREDS=User: rdpuser | Password: *m96319631Z-" >> $GITHUB_ENV
          sudo systemctl enable xrdp
          sudo systemctl restart xrdp
          sleep 5

      - name: نصب Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: برقراری اتصال Tailscale
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-ubuntu-${{ github.run_id }}

          retries=0
          while [ -z "$TSIP" ] && [ $retries -lt 10 ]; do
              TSIP=$(tailscale ip -4)
              sleep 5
              retries=$((retries + 1))
          done

          if [ -z "$TSIP" ]; then
              echo "آدرس IP تِیل‌اِسکِیل تخصیص داده نشد. خروج."
              exit 1
          fi

          echo "TAILSCALE_IP=$TSIP" >> $GITHUB_ENV
          echo "آدرس IP تِیل‌اِسکِیل: $TSIP"

      - name: تأیید دسترسی RDP
        run: |
          echo "آدرس IP تِیل‌اِسکِیل: $TAILSCALE_IP"
          if ! sudo netstat -tuln | grep :3389; then
              echo "XRDP روی پورت 3389 در حال گوش دادن نیست"
              exit 1
          fi

          sudo systemctl status xrdp
          echo "سرویس XRDP در حال اجرا و گوش دادن روی پورت 3389 است"

      - name: حفظ اتصال
        run: |
          echo ""
          echo "=== اطلاعات دسترسی RDP ==="
          echo "آدرس (Address): $TAILSCALE_IP"
          echo "نام کاربری (Username): rdpuser"
          echo "رمز عبور (Password): *m96319631Z-"
          echo "=========================="
          echo ""
          echo "محیط دسکتاپ: LXDE (سبک)"
          echo ""
          
          while true; do
              echo "[$(date)] RDP فعال - برای خاتمه دادن از دکمه لغو Workflow استفاده کنید"
              sleep 300
          done
